GET http://localhost:3001/products/?&search=&category=clothes&price=NORMAL&page_no=1
###

DELETE http://localhost:3001/products/timewear/
### 

POST http://localhost:3001/products/ 
Content-Type: application/json

{
    "name":"BlackBerry",
    "price":"20000",
    "category":"Mobiles", 
    "description": "BlackBerry comes with good camera quality and battery backup"
}

###

PUT http://localhost:3001/products/sonata
Content-Type: application/json

{
    "name":"TimeWear",
    "price":"250",
    "category":"Watches", 
    "description": "Time-wear comes in crisp and casual style with analog dial" 
}